--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 19/2/2024 15:18:43
-- Server version: 5.7.44
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE STEL_DB_STATIC;

--
-- Drop table `enviroment`
--
DROP TABLE IF EXISTS enviroment;

--
-- Drop table `operator`
--
DROP TABLE IF EXISTS operator;

--
-- Drop table `standard_has_endcap`
--
DROP TABLE IF EXISTS standard_has_endcap;

--
-- Drop table `standard_has_enviroments`
--
DROP TABLE IF EXISTS standard_has_enviroments;

--
-- Drop procedure `get_MaterialsByStandard`
--
DROP PROCEDURE IF EXISTS get_MaterialsByStandard;

--
-- Drop procedure `get_SettingsBySpecification`
--
DROP PROCEDURE IF EXISTS get_SettingsBySpecification;

--
-- Drop procedure `get_SpecificationByStandard`
--
DROP PROCEDURE IF EXISTS get_SpecificationByStandard;

--
-- Drop procedure `get_StandardTree`
--
DROP PROCEDURE IF EXISTS get_StandardTree;

--
-- Drop table `specification_has_configuration`
--
DROP TABLE IF EXISTS specification_has_configuration;

--
-- Drop procedure `get_ConditionalPeriodsbyStandard`
--
DROP PROCEDURE IF EXISTS get_ConditionalPeriodsbyStandard;

--
-- Drop table `standard_has_conditionalperiod`
--
DROP TABLE IF EXISTS standard_has_conditionalperiod;

--
-- Drop procedure `get_Standards`
--
DROP PROCEDURE IF EXISTS get_Standards;

--
-- Drop table `standard`
--
DROP TABLE IF EXISTS standard;

--
-- Drop table `specification`
--
DROP TABLE IF EXISTS specification;

--
-- Drop procedure `get_Material`
--
DROP PROCEDURE IF EXISTS get_Material;

--
-- Drop table `material`
--
DROP TABLE IF EXISTS material;

--
-- Set default database
--
USE STEL_DB_STATIC;

--
-- Create table `material`
--
CREATE TABLE material (
  id int(11) UNSIGNED NOT NULL,
  name varchar(50) NOT NULL,
  type varchar(40) NOT NULL,
  createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Material of Hoop',
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `get_Material`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE get_Material ()
BEGIN

  SELECT
    m.id AS idMaterial,
    m.name AS materialName,
    m.type AS materialType
  FROM material m;

END
$$

DELIMITER ;

--
-- Create table `specification`
--
CREATE TABLE specification (
  id int(11) UNSIGNED NOT NULL,
  material int(11) UNSIGNED NOT NULL,
  name varchar(50) NOT NULL,
  createdAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Specification of material',
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE specification
ADD CONSTRAINT FK_specification_material_id FOREIGN KEY (material)
REFERENCES material (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `standard`
--
CREATE TABLE standard (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Standards: ISO, IRAM, ...',
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `get_Standards`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE get_Standards ()
BEGIN

  SELECT
    s.id AS idStandard,
    s.name AS standardName
  FROM standard s;

END
$$

DELIMITER ;

--
-- Create table `standard_has_conditionalperiod`
--
CREATE TABLE standard_has_conditionalperiod (
  id int(11) UNSIGNED NOT NULL,
  standard int(11) UNSIGNED NOT NULL,
  minwall int(11) UNSIGNED NOT NULL,
  maxwall int(11) UNSIGNED NOT NULL,
  time varchar(12) NOT NULL,
  createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedtAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Conditional Period related to Standard',
ROW_FORMAT = DYNAMIC;

--
-- Create index `UK_cond_period` on table `standard_has_conditionalperiod`
--
ALTER TABLE standard_has_conditionalperiod
ADD UNIQUE INDEX UK_cond_period (standard, id);

--
-- Create foreign key
--
ALTER TABLE standard_has_conditionalperiod
ADD CONSTRAINT FK_cond_period_standard_id FOREIGN KEY (standard)
REFERENCES standard (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

DELIMITER $$

--
-- Create procedure `get_ConditionalPeriodsbyStandard`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE get_ConditionalPeriodsbyStandard (IN idStandard int UNSIGNED)
BEGIN

  SELECT
    cp.id AS idCondPeriod,
    cp.minwall AS minWall,
    cp.maxwall AS maxWall,
    cp.time AS condPeriod
  FROM standard_has_conditionalperiod cp
  WHERE cp.standard = idStandard
  ORDER BY cp.minwall;

END
$$

DELIMITER ;

--
-- Create table `specification_has_configuration`
--
CREATE TABLE specification_has_configuration (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  specification int(11) UNSIGNED NOT NULL,
  standard int(11) UNSIGNED NOT NULL,
  time smallint(6) UNSIGNED NOT NULL,
  temperature tinyint(4) UNSIGNED NOT NULL,
  createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Conditional period by Specification',
ROW_FORMAT = DYNAMIC;

--
-- Create index `FK_period_by_material_material_id` on table `specification_has_configuration`
--
ALTER TABLE specification_has_configuration
ADD INDEX FK_period_by_material_material_id (specification);

--
-- Create foreign key
--
ALTER TABLE specification_has_configuration
ADD CONSTRAINT FK_period_by_material_specification_id FOREIGN KEY (specification)
REFERENCES specification (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE specification_has_configuration
ADD CONSTRAINT FK_period_by_material_standard_id FOREIGN KEY (standard)
REFERENCES standard (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

DELIMITER $$

--
-- Create procedure `get_StandardTree`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE get_StandardTree ()
BEGIN

  CREATE TEMPORARY TABLE IF NOT EXISTS standardPeriods AS (SELECT
      cp.standard AS idStandard,
      JSON_ARRAYAGG(JSON_OBJECT('id', cp.id,
      'min_wall', cp.minwall,
      'max_wall', cp.maxwall,
      'period', cp.time)) AS condPeriods
    FROM standard_has_conditionalperiod cp
    GROUP BY cp.standard);

  CREATE TEMPORARY TABLE IF NOT EXISTS specificationClassification AS (SELECT
      pbs.standard AS idStandard,
      pbs.specification AS idSpecification,
      m.id AS idMaterial,
      JSON_OBJECT('idSpecification', pbs.specification,
      'specification', s1.name,
      'mySettings', JSON_ARRAYAGG(JSON_OBJECT('id', pbs.id,
      'data', JSON_OBJECT('h', pbs.time,
      'm', pbs.seconds,
      'temp', pbs.temperature)))) AS mySpecs
    FROM specification_has_configuration pbs
      INNER JOIN specification s1
        ON pbs.specification = s1.id
      INNER JOIN material m
        ON s1.material = m.id
    GROUP BY idStandard,
             idSpecification,
             idMaterial);

  CREATE TEMPORARY TABLE IF NOT EXISTS materialClassification (SELECT
      sc.idStandard AS idStandard,
      sc.idMaterial AS idMaterial,
      JSON_OBJECT('idMaterial', sc.idMaterial,
      'material', m.name,
      'type', m.type,
      'mySpecs', JSON_ARRAYAGG(sc.mySpecs)) AS myMaterials
    FROM specificationClassification sc
      INNER JOIN material m
        ON m.id = sc.idMaterial
    GROUP BY idStandard,
             idMaterial);

  SELECT
    mc.idStandard AS idStandard,
    JSON_OBJECT('id', s.id,
    'standard', s.name,
    'conditionalPeriods', (SELECT
        sp.condPeriods
      FROM standardPeriods sp
      WHERE sp.idStandard = mc.idStandard),
    'myMaterials', JSON_ARRAYAGG(mc.myMaterials)) AS myStandards
  FROM materialClassification mc
    INNER JOIN standard s
      ON s.id = mc.idStandard
  GROUP BY idStandard;

  DROP TABLE IF EXISTS standardPeriods;
  DROP TABLE IF EXISTS specificationClassification;
  DROP TABLE IF EXISTS materialClassification;

END
$$

--
-- Create procedure `get_SpecificationByStandard`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE get_SpecificationByStandard (IN idStandard int UNSIGNED, IN idMaterial int UNSIGNED)
BEGIN

  SELECT
    m.id AS idMaterial,
    s.id AS idSpecification,
    s.name AS specificationName
  FROM specification_has_configuration pbs
    INNER JOIN specification s
      ON pbs.specification = s.id
    INNER JOIN material m
      ON s.material = m.id
  WHERE pbs.standard = idStandard
  AND m.id = idMaterial
  GROUP BY pbs.standard,
           idMaterial,
           idSpecification;

END
$$

--
-- Create procedure `get_SettingsBySpecification`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE get_SettingsBySpecification (IN idStandard int UNSIGNED, IN idMaterial int UNSIGNED, IN idSpecification int UNSIGNED)
BEGIN

  SELECT
    pbs.id AS idSetting,
    pbs.time AS time,
    pbs.temperature AS temperature
  FROM specification_has_configuration pbs
    INNER JOIN specification s
      ON pbs.specification = s.id
    INNER JOIN material m
      ON s.material = m.id
  WHERE pbs.standard = idStandard
  AND m.id = idMaterial
  AND s.id = idSpecification;

END
$$

--
-- Create procedure `get_MaterialsByStandard`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE get_MaterialsByStandard (IN idStandard int UNSIGNED)
BEGIN

  SELECT
    m.id AS idMaterial,
    m.name AS materialName,
    m.type AS materialType
  FROM specification_has_configuration pbs
    INNER JOIN specification s
      ON pbs.specification = s.id
    INNER JOIN material m
      ON s.material = m.id
  WHERE pbs.standard = idStandard
  GROUP BY idStandard,
           idMaterial;

END
$$

DELIMITER ;

--
-- Create table `standard_has_enviroments`
--
CREATE TABLE standard_has_enviroments (
  idStandard int(11) UNSIGNED NOT NULL,
  idEnviroment int(11) UNSIGNED NOT NULL,
  createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Standards posible enviroments',
ROW_FORMAT = DYNAMIC;

--
-- Create index `UK_Standard_has_Enviroments` on table `standard_has_enviroments`
--
ALTER TABLE standard_has_enviroments
ADD UNIQUE INDEX UK_Standard_has_Enviroments (idStandard, idEnviroment);

--
-- Create table `standard_has_endcap`
--
CREATE TABLE standard_has_endcap (
  id int(11) UNSIGNED NOT NULL,
  standard int(11) UNSIGNED NOT NULL,
  type varchar(10) NOT NULL,
  createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `operator`
--
CREATE TABLE operator (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  familyname varchar(50) NOT NULL,
  createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedtAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Operator available',
ROW_FORMAT = DYNAMIC;

--
-- Create table `enviroment`
--
CREATE TABLE enviroment (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  enviroment varchar(255) DEFAULT NULL,
  createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Enviroments',
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table material
--
INSERT INTO material VALUES
(0, 'PE', 'Plastico', '2023-12-15 12:45:36', '2024-01-08 23:29:09'),
(1, 'PBC', 'Plastico', '2023-12-20 12:57:44', '2024-01-08 23:29:09');

-- 
-- Dumping data for table standard
--
INSERT INTO standard VALUES
(1, 'IRAM-4567', '2023-12-18 21:16:48', NULL),
(2, 'ISO-1167-1996', '2023-12-04 21:48:00', NULL);

-- 
-- Dumping data for table specification
--
INSERT INTO specification VALUES
(0, 0, 'PE100', '2023-12-15 12:46:03'),
(1, 0, 'PE50', '2023-12-18 20:06:57'),
(2, 1, 'PBC-200', '2023-12-20 13:03:02');

-- Table STEL_DB_STATIC.standard_has_enviroments does not contain any data (it is empty)

-- Table STEL_DB_STATIC.standard_has_endcap does not contain any data (it is empty)

-- 
-- Dumping data for table standard_has_conditionalperiod
--
INSERT INTO standard_has_conditionalperiod VALUES
(0, 1, 0, 3, '1 h ± 5 min', '2023-12-04 21:48:36', '2024-01-08 23:29:36'),
(1, 1, 3, 8, '3 h ± 15 min', '2023-12-04 21:49:27', '2024-01-08 23:29:36'),
(2, 1, 8, 16, '6 h ± 30 min', '2023-12-04 21:56:39', '2024-01-08 23:29:36'),
(3, 1, 16, 32, '10 h ± 1 h', '2023-12-04 21:56:39', '2024-01-08 23:29:36'),
(4, 1, 32, 9999999, '16 h ± 1 h', '2023-12-04 21:56:39', '2024-01-08 23:29:36');

-- 
-- Dumping data for table specification_has_configuration
--
INSERT INTO specification_has_configuration VALUES
(1, 0, 1, 1000, 20, '2024-01-08 00:00:00', '2024-01-09 02:15:44'),
(2, 1, 2, 10, 150, '2024-01-08 00:00:00', '2024-01-08 00:00:00'),
(3, 1, 1, 30, 50, '2024-01-08 00:00:00', '2024-01-09 02:16:05'),
(4, 2, 1, 60, 50, '2024-01-08 00:00:00', '2024-01-08 00:00:00'),
(5, 0, 1, 100, 90, '2024-01-08 23:13:53', '2024-01-08 23:13:56');

-- Table STEL_DB_STATIC.operator does not contain any data (it is empty)

-- Table STEL_DB_STATIC.enviroment does not contain any data (it is empty)

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;