--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13/12/2023 11:13:39
-- Server version: 10.4.32
-- Client version: 4.1
--


-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS stel_db;

CREATE DATABASE IF NOT EXISTS stel_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

--
-- Set default database
--
USE stel_db;

--
-- Create table `test_sample`
--
CREATE TABLE IF NOT EXISTS test_sample (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  standard varchar(25) NOT NULL,
  condPeriod varchar(10) NOT NULL,
  material varchar(10) NOT NULL,
  specification varchar(6) NOT NULL,
  targettemp double NOT NULL,
  targetpressure double NOT NULL,
  diamreal int(11) UNSIGNED NOT NULL,
  diamnom int(11) UNSIGNED NOT NULL,
  wallthick int(11) UNSIGNED NOT NULL,
  lenfree int(11) UNSIGNED NOT NULL,
  lentotal int(11) UNSIGNED NOT NULL,
  createdAt datetime NOT NULL,
  updatedAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Test Sample information';

--
-- Create table `operator`
--
CREATE TABLE IF NOT EXISTS operator (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  familyname varchar(50) NOT NULL,
  createdAt datetime NOT NULL,
  updatedAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Operator available';

--
-- Create table `test_specimen`
--
CREATE TABLE IF NOT EXISTS test_specimen (
  id int(11) UNSIGNED NOT NULL,
  test_sample int(11) UNSIGNED NOT NULL,
  operator int(11) UNSIGNED NOT NULL,
  start datetime NOT NULL,
  end datetime NOT NULL,
  enviromental varchar(255) DEFAULT NULL,
  createdAt datetime NOT NULL,
  updatedAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Test specimen';

--
-- Create foreign key
--
ALTER TABLE test_specimen
ADD CONSTRAINT rela_specimen_operator FOREIGN KEY (operator)
REFERENCES operator (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE test_specimen
ADD CONSTRAINT rela_specimen_sample FOREIGN KEY (test_sample)
REFERENCES test_sample (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `test_data`
--
CREATE TABLE IF NOT EXISTS test_data (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  test_specimen int(11) UNSIGNED NOT NULL,
  pressure double NOT NULL,
  temperature double NOT NULL,
  time timestamp NOT NULL DEFAULT current_timestamp ON UPDATE CURRENT_TIMESTAMP,
  createdAt datetime NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Data Recollected from PLC';

--
-- Create index `IDX_test_data_test_specimen` on table `test_data`
--
ALTER TABLE test_data
ADD INDEX IDX_test_data_test_specimen (test_specimen);

--
-- Create foreign key
--
ALTER TABLE test_data
ADD CONSTRAINT rela_data_specimen FOREIGN KEY (test_specimen)
REFERENCES test_specimen (id) ON DELETE NO ACTION ON UPDATE CASCADE;

--
-- Create table `material`
--
CREATE TABLE IF NOT EXISTS material (
  id int(11) UNSIGNED NOT NULL,
  name varchar(50) NOT NULL,
  type varchar(40) NOT NULL,
  createdAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Material of Hoop';

--
-- Create table `specification`
--
CREATE TABLE IF NOT EXISTS specification (
  id int(11) UNSIGNED NOT NULL,
  material int(11) UNSIGNED NOT NULL,
  name varchar(50) NOT NULL,
  createdAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Specification of material';

--
-- Create foreign key
--
ALTER TABLE specification
ADD CONSTRAINT FK_specification_material_id FOREIGN KEY (material)
REFERENCES material (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `period_by_material`
--
CREATE TABLE IF NOT EXISTS period_by_material (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  material int(11) UNSIGNED NOT NULL,
  condStandard int(11) UNSIGNED NOT NULL,
  createdAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Conditional period by Material';

--
-- Create foreign key
--
ALTER TABLE period_by_material
ADD CONSTRAINT FK_period_by_material_material_id FOREIGN KEY (material)
REFERENCES material (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `standard`
--
CREATE TABLE IF NOT EXISTS standard (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  createdAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Standards: ISO, IRAM, ...';

--
-- Create table `cond_period`
--
CREATE TABLE IF NOT EXISTS cond_period (
  id int(11) UNSIGNED NOT NULL,
  standard int(11) UNSIGNED NOT NULL,
  minwall int(11) UNSIGNED NOT NULL,
  maxwall int(11) UNSIGNED NOT NULL,
  hourscond int(3) UNSIGNED NOT NULL,
  errcond int(11) UNSIGNED NOT NULL,
  createdAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Conditional Period related to Standard';

--
-- Create index `UK_cond_period` on table `cond_period`
--
ALTER TABLE cond_period
ADD UNIQUE INDEX UK_cond_period (standard, id);

--
-- Create foreign key
--
ALTER TABLE cond_period
ADD CONSTRAINT FK_cond_period_standard_id FOREIGN KEY (standard)
REFERENCES standard (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table test_sample
--
-- Table stel_db.test_sample does not contain any data (it is empty)

-- 
-- Dumping data for table operator
--
-- Table stel_db.operator does not contain any data (it is empty)

-- 
-- Dumping data for table test_specimen
--
-- Table stel_db.test_specimen does not contain any data (it is empty)

-- 
-- Dumping data for table material
--
-- Table stel_db.material does not contain any data (it is empty)

-- 
-- Dumping data for table standard
--
INSERT INTO standard VALUES
(0, 'ISO-1167-1996', '2023-12-04 21:48:00');

-- 
-- Dumping data for table test_data
--
-- Table stel_db.test_data does not contain any data (it is empty)

-- 
-- Dumping data for table specification
--
-- Table stel_db.specification does not contain any data (it is empty)

-- 
-- Dumping data for table period_by_material
--
-- Table stel_db.period_by_material does not contain any data (it is empty)

-- 
-- Dumping data for table cond_period
--
INSERT INTO cond_period VALUES
(0, 0, 0, 3, 60, 5, '2023-12-04 21:48:36'),
(1, 0, 3, 8, 180, 15, '2023-12-04 21:49:27'),
(2, 0, 8, 16, 360, 30, '2023-12-04 21:56:39'),
(3, 0, 16, 32, 600, 60, '2023-12-04 21:56:39'),
(4, 0, 32, 9999999, 960, 60, '2023-12-04 21:56:39');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;