CREATE TABLE `operator` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dni` INT UNSIGNED NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `familyname` VARCHAR(50) NOT NULL,
  `createdAt` DATETIME(4) NOT NULL DEFAULT CURRENT_TIMESTAMP(4),
  `updatedAt` DATETIME(4) NOT NULL DEFAULT CURRENT_TIMESTAMP(4) ON UPDATE CURRENT_TIMESTAMP(4),
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;