--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 16/12/2023 02:00:50
-- Server version: 5.7.44
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE STEL_DB_DATA;

--
-- Drop table `test_data`
--
DROP TABLE IF EXISTS test_data;

--
-- Drop table `test_specimen`
--
DROP TABLE IF EXISTS test_specimen;

--
-- Drop table `operator`
--
DROP TABLE IF EXISTS operator;

--
-- Drop table `test_sample`
--
DROP TABLE IF EXISTS test_sample;

--
-- Set default database
--
USE STEL_DB_DATA;

--
-- Create table `test_sample`
--
CREATE TABLE test_sample (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  standard varchar(25) NOT NULL,
  condPeriod varchar(10) NOT NULL,
  material varchar(10) NOT NULL,
  specification varchar(6) NOT NULL,
  targettemp double NOT NULL,
  targetpressure double NOT NULL,
  diamreal int(11) UNSIGNED NOT NULL,
  diamnom int(11) UNSIGNED NOT NULL,
  wallthick int(11) UNSIGNED NOT NULL,
  lenfree int(11) UNSIGNED NOT NULL,
  lentotal int(11) UNSIGNED NOT NULL,
  createdAt datetime NOT NULL,
  updatedAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Test Sample information';

--
-- Create table `operator`
--
CREATE TABLE operator (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  familyname varchar(50) NOT NULL,
  createdAt datetime NOT NULL,
  updatedAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Operator available';

--
-- Create table `test_specimen`
--
CREATE TABLE test_specimen (
  id int(11) UNSIGNED NOT NULL,
  test_sample int(11) UNSIGNED NOT NULL,
  operator int(11) UNSIGNED NOT NULL,
  start datetime NOT NULL,
  end datetime NOT NULL,
  enviromental varchar(255) DEFAULT NULL,
  createdAt datetime NOT NULL,
  updatedAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Test specimen';

--
-- Create foreign key
--
ALTER TABLE test_specimen
ADD CONSTRAINT rela_specimen_operator FOREIGN KEY (operator)
REFERENCES operator (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE test_specimen
ADD CONSTRAINT rela_specimen_sample FOREIGN KEY (test_sample)
REFERENCES test_sample (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `test_data`
--
CREATE TABLE test_data (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  test_specimen int(11) UNSIGNED NOT NULL,
  pressure double NOT NULL,
  temperature double NOT NULL,
  time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Data Recollected from PLC';

--
-- Create index `IDX_test_data_test_specimen` on table `test_data`
--
ALTER TABLE test_data
ADD INDEX IDX_test_data_test_specimen (test_specimen);

--
-- Create foreign key
--
ALTER TABLE test_data
ADD CONSTRAINT rela_data_specimen FOREIGN KEY (test_specimen)
REFERENCES test_specimen (id) ON DELETE NO ACTION ON UPDATE CASCADE;

-- 
-- Dumping data for table test_sample
--
-- Table stel_db.test_sample does not contain any data (it is empty)

-- 
-- Dumping data for table operator
--
-- Table stel_db.operator does not contain any data (it is empty)

-- 
-- Dumping data for table test_specimen
--
-- Table stel_db.test_specimen does not contain any data (it is empty)

-- 
-- Dumping data for table test_data
--
-- Table stel_db.test_data does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;