--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/1/2024 00:12:32
-- Server version: 5.7.44
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS STEL_DB_DATA;

CREATE DATABASE IF NOT EXISTS STEL_DB_DATA
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE STEL_DB_DATA;

--
-- Create table `operator`
--
CREATE TABLE IF NOT EXISTS operator (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  familyname varchar(50) NOT NULL,
  createdAt datetime NOT NULL,
  updatedAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Operator available';

--
-- Create table `test_sample`
--
CREATE TABLE IF NOT EXISTS test_sample (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  standard varchar(25) NOT NULL,
  condPeriod varchar(15) NOT NULL,
  material varchar(10) NOT NULL,
  specification varchar(6) NOT NULL,
  targettemp int(11) NOT NULL,
  targetpressure int(11) NOT NULL,
  diamreal int(11) UNSIGNED NOT NULL,
  diamnom int(11) UNSIGNED NOT NULL,
  wallthick int(11) UNSIGNED NOT NULL,
  lenfree int(11) UNSIGNED NOT NULL,
  lentotal int(11) UNSIGNED NOT NULL,
  createdAt datetime NOT NULL,
  updatedAt datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Test Sample information';

DELIMITER $$

--
-- Create function `sampleExists`
--
CREATE
DEFINER = 'root'@'%'
FUNCTION sampleExists (standard varchar(25), material varchar(10), specification varchar(6), diamnom int UNSIGNED, diamreal int UNSIGNED, wallthick int UNSIGNED, lenfree int UNSIGNED, lentotal int UNSIGNED, targetpressure int, targettemp int)
RETURNS int(11) UNSIGNED
BEGIN

  DECLARE idSample int UNSIGNED;

  SELECT
    ts.id INTO idSample
  FROM test_sample ts
  WHERE (ts.standard = standard
  AND ts.material = material
  AND ts.specification = specification
  AND ts.diamreal = diamreal
  AND ts.diamnom = diamnom
  AND ts.wallthick = wallthick
  AND ts.lenfree = lenfree
  AND ts.lentotal = lentotal
  AND ts.targettemp = targettemp
  AND ts.targetpressure = targetpressure)
  LIMIT 1;

  RETURN idSample;
END
$$

--
-- Create function `newSample`
--
CREATE
DEFINER = 'root'@'%'
FUNCTION newSample (standard varchar(25), material varchar(10), specification varchar(6), diamnom int UNSIGNED, diamreal int UNSIGNED, wallthick int UNSIGNED, lenfree int UNSIGNED, lentotal int UNSIGNED, targetpressure int, targettemp int, condPeriod varchar(15))
RETURNS int(11)
BEGIN

  DECLARE idSample int UNSIGNED;

  INSERT INTO test_sample (standard, condPeriod, material, specification, targettemp, targetpressure, diamreal, diamnom, wallthick, lenfree, lentotal, createdAt, updatedAt)
    VALUES (standard, condPeriod, material, specification, targettemp, targetpressure, diamreal, diamnom, wallthick, lenfree, lentotal, NOW(), NOW());

  SELECT
    ts.id INTO idSample
  FROM test_sample ts
  ORDER BY ts.id DESC
  LIMIT 1;

  RETURN idSample;
END
$$

--
-- Create procedure `insertSample`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE insertSample (IN standard varchar(25), IN material varchar(10), IN specification varchar(6), IN diamnom int UNSIGNED, IN diamreal int UNSIGNED, IN wallthick int UNSIGNED, IN lenfree int UNSIGNED, IN lentotal int UNSIGNED, IN targetpressure int, IN targettemp int,
OUT idSample int UNSIGNED)
BEGIN

  #DECLARE idSample int UNSIGNED;

  SET idSample = sampleExists(standard, material, specification, diamnom, diamreal, wallthick, lenfree, lentotal, targetpressure, targettemp);

  IF idSample IS NULL THEN
    SET idSample := newSample(standard, material, specification, diamnom, diamreal, wallthick, lenfree, lentotal, targetpressure, targettemp, 'h + min');
  END IF;

END
$$

DELIMITER ;

--
-- Create table `test_specimen`
--
CREATE TABLE IF NOT EXISTS test_specimen (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  test_sample int(11) UNSIGNED NOT NULL,
  operator int(11) UNSIGNED NOT NULL,
  start datetime NOT NULL,
  end datetime DEFAULT NULL,
  enviromental varchar(7) DEFAULT NULL,
  createdAt datetime NOT NULL,
  updatedAt datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Test specimen';

--
-- Create foreign key
--
ALTER TABLE test_specimen
ADD CONSTRAINT rela_specimen_operator FOREIGN KEY (operator)
REFERENCES operator (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE test_specimen
ADD CONSTRAINT rela_specimen_sample FOREIGN KEY (test_sample)
REFERENCES test_sample (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

DELIMITER $$

--
-- Create function `specimenExists`
--
CREATE
DEFINER = 'root'@'%'
FUNCTION specimenExists (idSample int UNSIGNED, start varbinary(255))
RETURNS int(11) UNSIGNED
BEGIN

  DECLARE idSpecimen int UNSIGNED;

  SELECT
    ts.id INTO idSpecimen
  FROM test_specimen ts
  WHERE (ts.test_sample = idSample
  AND ts.start = start)
  LIMIT 1;

  RETURN idSpecimen;
END
$$

--
-- Create function `newSpecimen`
--
CREATE
DEFINER = 'root'@'%'
FUNCTION newSpecimen (idSample int UNSIGNED, idOperator int UNSIGNED, start_ datetime, enviromental varchar(7))
RETURNS int(11)
BEGIN

  DECLARE idSpecimen int UNSIGNED;

  INSERT INTO test_specimen (test_sample, operator, start, end, enviromental, createdAt, updatedAt)
    VALUES (idSample, idOperator, start_, NULL, enviromental, NOW(), NOW());

  SELECT
    ts.id INTO idSpecimen
  FROM test_specimen ts
  ORDER BY ts.id DESC
  LIMIT 1;

  RETURN idSpecimen;
END
$$

--
-- Create procedure `insertSpecimen`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE insertSpecimen (IN idSample int UNSIGNED, IN idOperator int UNSIGNED, IN startDate datetime, IN endDate datetime, IN enviromental varchar(7), OUT idSpecimen int UNSIGNED)
BEGIN

  SET idSpecimen = specimenExists(idSample, startDate);

  IF idSpecimen IS NULL THEN
    SET idSpecimen := newSpecimen();
  END IF;

END
$$

--
-- Create procedure `countSpecimens`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE countSpecimens (IN idSample int UNSIGNED, OUT counts int)
BEGIN

  SELECT
    COUNT(ts.test_sample) INTO counts
  FROM test_specimen ts
  WHERE ts.test_sample = idSample;

END
$$

DELIMITER ;

--
-- Create table `test_data`
--
CREATE TABLE IF NOT EXISTS test_data (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  test_specimen int(11) UNSIGNED NOT NULL,
  pressure double NOT NULL,
  temperature double NOT NULL,
  createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Data Recollected from PLC';

--
-- Create index `IDX_test_data_test_specimen` on table `test_data`
--
ALTER TABLE test_data
ADD INDEX IDX_test_data_test_specimen (test_specimen);

--
-- Create foreign key
--
ALTER TABLE test_data
ADD CONSTRAINT FK_test_data_test_specimen_id FOREIGN KEY (test_specimen)
REFERENCES test_specimen (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

DELIMITER $$

--
-- Create procedure `insertData`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE insertData (IN idSpecimen int UNSIGNED, IN pressure double, IN temperature double)
BEGIN

  INSERT INTO test_data (test_specimen, pressure, temperature, time, createdAt)
    VALUES (idSpecimen, pressure, temperature, NOW(), NOW());

END
$$

DELIMITER ;

-- 
-- Dumping data for table test_sample
--
INSERT INTO test_sample VALUES
(1, 'ISO-1167-4560', '3h', 'PE', 'PE100', 20, 25, 50, 50, 5, 340, 560, '2024-01-02 00:00:00', '2024-01-02 00:00:00'),
(3, 'ISO-1167-4560', 'h + min', 'PE', 'PE50', 45, 34, 50, 50, 5, 180, 430, '2024-01-03 21:46:46', '2024-01-03 21:46:46');

-- 
-- Dumping data for table operator
--
INSERT INTO operator VALUES
(1, 'Pesta', 'pestingui', '2024-01-02 00:00:00', '2024-01-02 00:00:00');

-- 
-- Dumping data for table test_specimen
--
INSERT INTO test_specimen VALUES
(1, 1, 1, '2024-01-05 03:17:00', NULL, 'water', '2024-01-05 03:17:00', '2024-01-05 03:17:00');

-- 
-- Dumping data for table test_data
--
-- Table STEL_DB_DATA.test_data does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;