CREATE TABLE `sample` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID Sample',
  `standard` VARCHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Standard',
  `material` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Material',
  `specification` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Specification',
  `diamreal` INT UNSIGNED NOT NULL COMMENT 'Real Diameter',
  `diamnom` INT UNSIGNED NOT NULL COMMENT 'Nominal Diameter',
  `wallthick` INT UNSIGNED NOT NULL COMMENT 'Wall Thickness',
  `lentotal` INT UNSIGNED NOT NULL COMMENT 'Total Length',
  `lenfree` INT UNSIGNED NOT NULL COMMENT 'Length Free',
  `condPeriod` VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Conditional Period',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Test Sample information',
ROW_FORMAT = DYNAMIC;