--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28/8/2024 21:59:06
-- Server version: 8.3.0
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8mb4';

DROP DATABASE IF EXISTS data_db;

CREATE DATABASE IF NOT EXISTS data_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE data_db;

--
-- Create table `sample`
--
CREATE TABLE IF NOT EXISTS sample (
  id int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID Sample',
  standard varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Standard',
  material varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Material',
  specification varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Specification',
  diamreal int UNSIGNED NOT NULL COMMENT 'Real Diameter',
  diamnom int UNSIGNED NOT NULL COMMENT 'Nominal Diameter',
  wallthick int UNSIGNED NOT NULL COMMENT 'Wall Thickness',
  lentotal int UNSIGNED NOT NULL COMMENT 'Total Length',
  lenfree int UNSIGNED NOT NULL COMMENT 'Length Free',
  condPeriod varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Conditional Period',
  createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Test Sample information',
ROW_FORMAT = DYNAMIC;

--
-- Create index `UK_sample` on table `sample`
--
ALTER TABLE sample
ADD UNIQUE INDEX UK_sample (standard, specification, material, diamreal, diamnom, wallthick, lentotal, lenfree, condPeriod);

DELIMITER $$

--
-- Create function `hoopStress`
--
CREATE
DEFINER = 'root'@'localhost'
FUNCTION IF NOT EXISTS hoopStress (idSample int UNSIGNED, pressure int)
RETURNS int(11)
DETERMINISTIC
BEGIN

  SET @hoopResult = 0;

  SELECT
    (((pressure * (s.diamreal - s.wallthick)) / (10 * 2 * s.wallthick))) INTO @hoopResult
  FROM sample s
  WHERE s.id = idSample;

  RETURN @hoopResult;
END
$$

--
-- Create procedure `selectTests`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE IF NOT EXISTS selectTests ()
DETERMINISTIC
BEGIN

  SELECT
    ts.id AS idSample,
    ts.material AS material,
    ts.specification AS specification,
    ts.diamreal AS diameter,
    ts.wallthick AS wallThickness,
    ts.lenfree AS length
  --     selectTestsSpecimens(ts.id) AS mySpecimens
  FROM sample ts;

END
$$

DELIMITER ;

--
-- Create table `specimen`
--
CREATE TABLE IF NOT EXISTS specimen (
  id int UNSIGNED NOT NULL AUTO_INCREMENT,
  sample int UNSIGNED DEFAULT NULL,
  targetPressure int DEFAULT NULL,
  targetTemperature int DEFAULT NULL,
  operator varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'No operador',
  enviroment varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'No Entorno',
  testName varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'Sin nombre',
  endCap varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'Sin Tapa',
  failText varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Sin Fallas',
  remark varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Sin Observaciones',
  createdAt datetime NOT NULL,
  updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX UK_specimen (id, createdAt)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 910,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Test specimen',
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE specimen
ADD CONSTRAINT FK_test_specimen_test_sample_id FOREIGN KEY (sample)
REFERENCES sample (id) ON DELETE CASCADE;

DELIMITER $$

--
-- Create function `selectTestNumber`
--
CREATE
DEFINER = 'root'@'%'
FUNCTION IF NOT EXISTS selectTestNumber (idSpecimen int UNSIGNED)
RETURNS int(11) UNSIGNED
DETERMINISTIC
BEGIN
  SET @testNumber = 0;

  SET @sampleID = (SELECT
      ts.sample
    FROM specimen ts
    WHERE ts.id = idSpecimen);

  SELECT
    COUNT(*) INTO @testNumber
  FROM specimen ts
  WHERE ts.id <= idSpecimen
  AND ts.sample = @sampleID
  GROUP BY ts.sample;

  RETURN @testNumber;
END
$$

--
-- Create function `countSpecimens`
--
CREATE
DEFINER = 'root'@'%'
FUNCTION IF NOT EXISTS countSpecimens (standardIN text, materialIN text, specificationIN text, diameterNominalIN int UNSIGNED, diameterRealIN int UNSIGNED, wallthicknessIN int UNSIGNED, lengthFreeIN int UNSIGNED, lengthTotalIN int UNSIGNED)
RETURNS int(11) UNSIGNED
DETERMINISTIC
BEGIN
  SET @count = 0;

  WITH mySample (ID)
  AS
  (SELECT
      s.id AS ID
    FROM sample s
    WHERE s.standard LIKE standardIN
    AND s.material LIKE materialIN
    AND s.specification LIKE specificationIN
    AND s.diamnom = diameterNominalIN
    AND s.diamreal = diameterRealIN
    AND s.wallthick = wallthicknessIN
    AND s.lenfree = lengthFreeIN
    AND s.lentotal = lengthTotalIN)

  SELECT
    COUNT(*) INTO @count
  FROM specimen ts
  WHERE ts.sample = (SELECT
      ms.ID
    FROM mySample ms)
  GROUP BY ts.sample;

  RETURN @count;
END
$$

--
-- Create function `selectTestSample`
--
CREATE
DEFINER = 'root'@'localhost'
FUNCTION IF NOT EXISTS selectTestSample (idSample int UNSIGNED)
RETURNS json
DETERMINISTIC
BEGIN

  SET @result = NULL;

  SELECT
    JSON_OBJECT('idSample',
    sa.id,
    'standard',
    sa.standard,
    'material',
    sa.material,
    'specification',
    sa.specification,
    'diameterReal',
    sa.diamreal,
    'diameterNominal',
    sa.diamnom,
    'wallThickness',
    sa.wallthick,
    'lengthTotal',
    sa.lentotal,
    'lengthFree',
    sa.lenfree,
    'conditionalPeriod',
    sa.condPeriod,
    'count',
    countSpecimens(sa.standard, sa.material, sa.specification, sa.diamnom, sa.diamreal, sa.wallthick, sa.lenfree, sa.lentotal)) INTO @result
  FROM sample sa
  WHERE sa.id = idSample;

  RETURN @result;
END
$$

--
-- Create procedure `selectCompareTests`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE IF NOT EXISTS selectCompareTests (IN arraySpecimens text)
DETERMINISTIC
BEGIN

  SELECT
    (selectTestSample(sa.id)) AS 'mySample',
    (selectTestSpecimen(se.id)) AS 'mySpecimen'
  FROM specimen se
    INNER JOIN sample sa
      ON se.sample = sa.id
  WHERE FIND_IN_SET(se.id, arraySpecimens) > 0;

END
$$

DELIMITER ;

--
-- Create table `data`
--
CREATE TABLE IF NOT EXISTS data (
  id int UNSIGNED NOT NULL AUTO_INCREMENT,
  specimen int UNSIGNED NOT NULL,
  pressure double NOT NULL,
  temperature double NOT NULL,
  ambient double NOT NULL,
  createdAt datetime(4) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 58,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Data Recollected from PLC',
ROW_FORMAT = DYNAMIC;

--
-- Create index `IDX_test_data_test_specimen` on table `data`
--
ALTER TABLE data
ADD INDEX IDX_test_data_test_specimen (specimen);

--
-- Create index `UK_data` on table `data`
--
ALTER TABLE data
ADD UNIQUE INDEX UK_data (specimen, pressure, temperature, ambient, createdAt);

--
-- Create foreign key
--
ALTER TABLE data
ADD CONSTRAINT FK_data_specimen_id FOREIGN KEY (specimen)
REFERENCES specimen (id);

DELIMITER $$

--
-- Create function `selectTestLimit`
--
CREATE
DEFINER = 'root'@'%'
FUNCTION IF NOT EXISTS selectTestLimit (idSpecimen int UNSIGNED, isASC tinyint UNSIGNED)
RETURNS datetime
DETERMINISTIC
BEGIN

  SET @Time = NULL;

  IF isASC = 0 THEN
    SELECT
      td.createdAt INTO @Time
    FROM data td
    WHERE td.specimen = idSpecimen
    ORDER BY td.createdAt ASC LIMIT 1;
  ELSE
    SELECT
      td.createdAt INTO @Time
    FROM data td
    WHERE td.specimen = idSpecimen
    ORDER BY td.createdAt DESC LIMIT 1;
  END IF;

  RETURN @Time;
END
$$

--
-- Create function `selectTestsSpecimens`
--
CREATE
DEFINER = 'root'@'%'
FUNCTION IF NOT EXISTS selectTestsSpecimens (idSample int UNSIGNED)
RETURNS json
DETERMINISTIC
BEGIN
  SET @myResult = NULL;

  WITH preResults
  AS
  (SELECT
      ts.id,
      ts.targetPressure,
      ts.targetTemperature,
      ts.operator,
      selectTestNumber(ts.id) AS testNumber,
      (selectTestLimit(ts.id, 0)) AS beginTime,
      (selectTestLimit(ts.id, 1)) AS endTime
    FROM specimen ts
    WHERE ts.sample = idSample)

  (SELECT
      JSON_ARRAYAGG(JSON_OBJECT('idSpecimen', pr.id,
      'testNumber', ROW_NUMBER() OVER (
      ORDER BY pr.id),
      'targetPressure', pr.targetPressure,
      'targetTemperature', pr.targetTemperature,
      'operator', pr.operator,
      'testNumber', pr.testNumber,
      'beginTime', DATE_FORMAT(pr.beginTime, '%d/%m/%Y %H:%i:%s'),
      'endTime', DATE_FORMAT(pr.endTime, '%d/%m/%Y %H:%i:%s'),
      'duration', DATE_FORMAT(TIMEDIFF(pr.endTime, pr.beginTime), '%H:%i:%s'))) INTO @myResult
    FROM preResults pr
    ORDER BY pr.id DESC);

  RETURN @myResult;
END
$$

--
-- Create procedure `selectTest`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE IF NOT EXISTS selectTest (IN idSpecimenIN int UNSIGNED)
DETERMINISTIC
BEGIN

  SET @countSpecimens = (SELECT
      COUNT(*)
    FROM specimen spe
    WHERE spe.id = idSpecimenIN
    GROUP BY spe.sample);
  SET @beginTime = DATE_FORMAT((SELECT
      MIN(d.createdAt)
    FROM data d
    WHERE d.specimen = idSpecimenIN), '%d/%m/%Y %H:%i:%s');
  SET @endTime = DATE_FORMAT((SELECT
      MAX(d.createdAt)
    FROM data d
    WHERE d.specimen = idSpecimenIN), '%d/%m/%Y %H:%i:%s');
  SET @timeDiff = DATE_FORMAT(TIMEDIFF(@endTime, @beginTime), '%H:%i:%s');

  SELECT
    s.id AS idSpecimen,
    s.sample AS idSample,
    s1.standard AS standard,
    s1.material AS material,
    s1.specification AS specification,
    s1.diamreal AS diameterReal,
    s1.diamnom AS diameterNominal,
    s1.wallthick AS wallThickness,
    s1.lenfree AS lengthFree,
    s1.lentotal AS lengthTotal,
    s1.condPeriod AS conditionalPeriod,
    @countSpecimens AS specimensCount,
    (IF(s.targetPressure IS NULL, NULL, s.targetPressure)) AS targetPressure,
    (IF(s.targetTemperature IS NULL, NULL, s.targetTemperature)) AS targetTemperature,
    s.operator AS operator,
    s.enviroment AS enviroment,
    s.testName AS testName,
    s.endCap AS endCap,
    s.failText AS failText,
    s.remark AS remark,
    @beginTime AS beginTime,
    @endTime AS endTime,
    @timeDiff AS duration
  FROM specimen s
    INNER JOIN sample s1
      ON s.sample = s1.id
  WHERE s.id = idSpecimenIN;

END
$$

--
-- Create procedure `selectData`
--
CREATE
DEFINER = 'root'@'%'
PROCEDURE IF NOT EXISTS selectData (IN idSpecimenIN int UNSIGNED, IN intervalIN int UNSIGNED, IN timeTypeIN char(1))
DETERMINISTIC
BEGIN

  SET @initTime = (SELECT
      td.createdAt
    FROM data td
    WHERE td.specimen = idSpecimenIN
    ORDER BY td.createdAt ASC LIMIT 1);

  IF (intervalIN = 1
    AND timeTypeIN LIKE 's') THEN
    WITH subTable (id, pressure, temperature, ambient, createdAt)
    AS
    (SELECT
        ROW_NUMBER() OVER (
        ORDER BY TIMESTAMPDIFF(SECOND, @initTime, d.createdAt)) AS id,
        d.pressure AS pressure,
        d.temperature AS temperature,
        d.ambient AS ambient,
        d.createdAt
      FROM data d
      WHERE d.specimen = idSpecimenIN)
    SELECT
      st.id,
      IF(timeTypeIN LIKE 'h', CAST(st.id / 360 AS UNSIGNED), IF(timeTypeIN LIKE 'm', CAST(st.id / 6 AS UNSIGNED), CAST(st.id AS UNSIGNED))) AS `key`,
      st.pressure,
      st.temperature,
      st.ambient,
      st.createdAt
    FROM subTable st;
  ELSE
    WITH subTable (id, pressure, temperature, ambient, createdAt)
    AS
    (SELECT
        ROW_NUMBER() OVER (
        ORDER BY TIMESTAMPDIFF(SECOND, @initTime, d.createdAt)) AS id,
        d.pressure AS pressure,
        d.temperature AS temperature,
        d.ambient AS ambient,
        d.createdAt
      FROM data d
      WHERE d.specimen = idSpecimenIN)

    SELECT
      st.id,
      IF(timeTypeIN LIKE 'h', CAST(st.id / 360 AS UNSIGNED), IF(timeTypeIN LIKE 'm', CAST(st.id / 6 AS UNSIGNED), CAST(st.id AS UNSIGNED))) AS `key`,
      st.pressure,
      st.temperature,
      st.ambient,
      st.createdAt
    FROM subTable st
    WHERE st.id % intervalIN = 1;
  END IF;
END
$$

DELIMITER ;

CREATE USER IF NOT EXISTS 'dataCollector'@'%' IDENTIFIED WITH caching_sha2_password PASSWORD EXPIRE NEVER;
GRANT SELECT, INSERT ON data_db.* TO 'dataCollector'@'%';
GRANT SELECT, INSERT ON TABLE data_db.data TO 'dataCollector'@'%';
GRANT SELECT, INSERT ON TABLE data_db.sample TO 'dataCollector'@'%';
GRANT SELECT, INSERT ON TABLE data_db.specimen TO 'dataCollector'@'%';
GRANT EXECUTE ON FUNCTION data_db.countspecimens TO 'dataCollector'@'%';
GRANT EXECUTE ON FUNCTION static_db.selectoperators_into_json TO 'dataCollector'@'%';
GRANT EXECUTE ON FUNCTION static_db.selectstandard_into_json TO 'dataCollector'@'%';

CREATE USER IF NOT EXISTS 'databaseManager'@'%' IDENTIFIED WITH caching_sha2_password PASSWORD EXPIRE NEVER;
GRANT SELECT ON TABLE static_db.material TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.deleteconditionalperiod TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.deleteendcap TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.deleteenviroment TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.deletematerial TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.deleteoperator TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.deleterelatedmaterial TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.deletesettingsspecification TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.deletespecification TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.deletestandard TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.deletetesttype TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.insertconditionalperiod TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.insertendcap TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.insertenviroment TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.insertmaterial TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.insertoperator TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.insertrelatedmaterial TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.insertsettingsspecification TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.insertspecification TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.insertstandard TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.inserttesttype TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.selectmaterialsjson TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.selectoperatorsjson TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.selectstandardsjson TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.updatematerial TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.updateoperator TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.updatesettingsspecification TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.updatespecification TO 'databaseManager'@'%';
GRANT EXECUTE ON PROCEDURE static_db.updatestandard TO 'databaseManager'@'%';

CREATE USER IF NOT EXISTS 'mysql.infoschema'@'localhost' IDENTIFIED WITH caching_sha2_password PASSWORD EXPIRE DEFAULT ACCOUNT LOCK;
GRANT SELECT, AUDIT_ABORT_EXEMPT, FIREWALL_EXEMPT, SYSTEM_USER ON *.* TO 'mysql.infoschema'@'localhost';

CREATE USER IF NOT EXISTS 'mysql.session'@'localhost' IDENTIFIED WITH caching_sha2_password PASSWORD EXPIRE DEFAULT ACCOUNT LOCK;
GRANT SHUTDOWN, SUPER, CLONE_ADMIN, CONNECTION_ADMIN, AUDIT_ABORT_EXEMPT, AUTHENTICATION_POLICY_ADMIN, BACKUP_ADMIN, FIREWALL_EXEMPT, PERSIST_RO_VARIABLES_ADMIN, SESSION_VARIABLES_ADMIN, SYSTEM_USER, SYSTEM_VARIABLES_ADMIN ON *.* TO 'mysql.session'@'localhost';
GRANT SELECT ON performance_schema.* TO 'mysql.session'@'localhost';
GRANT SELECT ON TABLE mysql.user TO 'mysql.session'@'localhost';

CREATE USER IF NOT EXISTS 'mysql.sys'@'localhost' IDENTIFIED WITH caching_sha2_password PASSWORD EXPIRE DEFAULT ACCOUNT LOCK;
GRANT AUDIT_ABORT_EXEMPT, FIREWALL_EXEMPT, SYSTEM_USER ON *.* TO 'mysql.sys'@'localhost';
GRANT TRIGGER ON sys.* TO 'mysql.sys'@'localhost';
GRANT SELECT ON TABLE sys.sys_config TO 'mysql.sys'@'localhost';

CREATE USER IF NOT EXISTS 'reportGenerator'@'%' IDENTIFIED WITH caching_sha2_password PASSWORD EXPIRE NEVER;
GRANT EXECUTE ON *.* TO 'reportGenerator'@'%';
GRANT SELECT, UPDATE ON TABLE data_db.sample TO 'reportGenerator'@'%';
GRANT SELECT, UPDATE, DELETE ON TABLE data_db.specimen TO 'reportGenerator'@'%';
GRANT SELECT ON TABLE static_db.operator TO 'reportGenerator'@'%';
GRANT EXECUTE ON PROCEDURE data_db.selectdata TO 'reportGenerator'@'%';
GRANT EXECUTE ON FUNCTION static_db.selectstandard_into_json TO 'reportGenerator'@'%';

CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED WITH caching_sha2_password PASSWORD EXPIRE DEFAULT;
GRANT USAGE ON *.* TO 'root'@'%'
WITH GRANT OPTION;
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROLE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE USER, CREATE VIEW, DELETE, DROP, DROP ROLE, EVENT, EXECUTE, FILE, INDEX, INSERT, LOCK TABLES, PROCESS, REFERENCES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SELECT, SHOW DATABASES, SHOW VIEW, SHUTDOWN, SUPER, TRIGGER, UPDATE, BINLOG_ENCRYPTION_ADMIN, CLONE_ADMIN, CONNECTION_ADMIN, ENCRYPTION_KEY_ADMIN, FIREWALL_EXEMPT, FLUSH_OPTIMIZER_COSTS, FLUSH_STATUS, FLUSH_TABLES, FLUSH_USER_RESOURCES, GROUP_REPLICATION_ADMIN, GROUP_REPLICATION_STREAM, INNODB_REDO_LOG_ARCHIVE, INNODB_REDO_LOG_ENABLE, PASSWORDLESS_USER_ADMIN, PERSIST_RO_VARIABLES_ADMIN, REPLICATION_APPLIER, REPLICATION_SLAVE_ADMIN, RESOURCE_GROUP_ADMIN, RESOURCE_GROUP_USER, ROLE_ADMIN, SENSITIVE_VARIABLES_OBSERVER, SERVICE_CONNECTION_ADMIN, SESSION_VARIABLES_ADMIN, SET_ANY_DEFINER, SHOW_ROUTINE, SYSTEM_USER, SYSTEM_VARIABLES_ADMIN, TABLE_ENCRYPTION_ADMIN, TRANSACTION_GTID_TAG, XA_RECOVER_ADMIN, TELEMETRY_LOG_ADMIN, ALLOW_NONEXISTENT_DEFINER, APPLICATION_PASSWORD_ADMIN, AUDIT_ABORT_EXEMPT, AUDIT_ADMIN, AUTHENTICATION_POLICY_ADMIN, BACKUP_ADMIN, BINLOG_ADMIN ON *.* TO 'root'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER ON data_db.* TO 'root'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER ON static_db.* TO 'root'@'%';

CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED WITH caching_sha2_password PASSWORD EXPIRE DEFAULT;
GRANT USAGE ON *.* TO 'root'@'localhost'
WITH GRANT OPTION;
GRANT ALLOW_NONEXISTENT_DEFINER, ALTER, ALTER ROUTINE, APPLICATION_PASSWORD_ADMIN, AUDIT_ABORT_EXEMPT, AUDIT_ADMIN, AUTHENTICATION_POLICY_ADMIN, BACKUP_ADMIN, BINLOG_ADMIN, BINLOG_ENCRYPTION_ADMIN, CLONE_ADMIN, CONNECTION_ADMIN, CREATE, CREATE ROLE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE USER, CREATE VIEW, DELETE, DROP, DROP ROLE, ENCRYPTION_KEY_ADMIN, EVENT, EXECUTE, FILE, FIREWALL_EXEMPT, FLUSH_OPTIMIZER_COSTS, FLUSH_STATUS, FLUSH_TABLES, FLUSH_USER_RESOURCES, GROUP_REPLICATION_ADMIN, GROUP_REPLICATION_STREAM, INDEX, INNODB_REDO_LOG_ARCHIVE, INNODB_REDO_LOG_ENABLE, INSERT, LOCK TABLES, PASSWORDLESS_USER_ADMIN, PERSIST_RO_VARIABLES_ADMIN, PROCESS, REFERENCES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, REPLICATION_APPLIER, REPLICATION_SLAVE_ADMIN, RESOURCE_GROUP_ADMIN, RESOURCE_GROUP_USER, ROLE_ADMIN, SELECT, SENSITIVE_VARIABLES_OBSERVER, SERVICE_CONNECTION_ADMIN, SESSION_VARIABLES_ADMIN, SET_ANY_DEFINER, SHOW DATABASES, SHOW VIEW, SHOW_ROUTINE, SHUTDOWN, SUPER, SYSTEM_USER, SYSTEM_VARIABLES_ADMIN, TABLE_ENCRYPTION_ADMIN, TELEMETRY_LOG_ADMIN, TRANSACTION_GTID_TAG, TRIGGER, UPDATE, XA_RECOVER_ADMIN ON *.* TO 'root'@'localhost';

GRANT PROXY ON ''@'' TO 'root'@'%' WITH GRANT OPTION;

GRANT PROXY ON ''@'' TO 'root'@'localhost' WITH GRANT OPTION;

-- Table data_db.sample does not contain any data (it is empty)

-- Table data_db.specimen does not contain any data (it is empty)

-- Table data_db.data does not contain any data (it is empty)

--
-- Set default database
--
USE data_db;

DELIMITER $$

--
-- Create trigger `NewSample`
--
CREATE
DEFINER = 'root'@'localhost'
TRIGGER IF NOT EXISTS NewSample
BEFORE INSERT
ON sample
FOR EACH ROW
BEGIN

  DECLARE row_id int UNSIGNED;

  SELECT
    s.id INTO row_id
  FROM sample s
  WHERE s.standard LIKE NEW.standard
  AND s.material LIKE NEW.material
  AND s.specification LIKE NEW.specification
  AND s.diamreal = NEW.diamreal
  AND s.diamnom = NEW.diamnom
  AND s.lentotal = NEW.lentotal
  AND s.lenfree = NEW.lenfree
  AND s.wallthick = NEW.wallthick;

  IF row_id IS NOT NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = row_id;
  END IF;

END
$$

--
-- Create trigger `DeleteTestSample`
--
CREATE
DEFINER = 'root'@'%'
TRIGGER IF NOT EXISTS DeleteTestSample
AFTER DELETE
ON specimen
FOR EACH ROW
BEGIN

  SET @countTests = 0;

  SELECT
    COUNT(*) INTO @countTests
  FROM specimen ts
  WHERE ts.sample = OLD.sample;

  IF @countTests < 1 THEN

    DELETE LOW_PRIORITY QUICK
      FROM sample
    WHERE sample.id = OLD.sample;

  END IF;

END
$$

--
-- Create trigger `DeleteTest`
--
CREATE
DEFINER = 'root'@'%'
TRIGGER IF NOT EXISTS DeleteTest
BEFORE DELETE
ON specimen
FOR EACH ROW
BEGIN

  DELETE LOW_PRIORITY QUICK
    FROM data td
  WHERE td.specimen = OLD.id;

END
$$

DELIMITER ;

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;