--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 30/5/2024 19:42:30
-- Server version: 8.3.0
--

SET NAMES 'utf8mb4';

INSERT INTO stel_db_static.conditional_period(id, standard, time, minwall, maxwall, createdAt, updatedtAt) VALUES
(0, 1, '1 h ± 5 min', 0, 3, '2023-12-04 21:48:36', '2024-03-26 00:23:39');
INSERT INTO stel_db_static.conditional_period(id, standard, time, minwall, maxwall, createdAt, updatedtAt) VALUES
(1, 1, '3 h ± 15 min', 3, 8, '2023-12-04 21:49:27', '2024-03-26 00:23:59');
INSERT INTO stel_db_static.conditional_period(id, standard, time, minwall, maxwall, createdAt, updatedtAt) VALUES
(2, 1, '6 h ± 30 min', 8, 16, '2023-12-04 21:56:39', '2024-03-26 00:24:09');
INSERT INTO stel_db_static.conditional_period(id, standard, time, minwall, maxwall, createdAt, updatedtAt) VALUES
(3, 1, '10 h ± 1 h', 16, 32, '2023-12-04 21:56:39', '2024-03-26 00:24:18');
INSERT INTO stel_db_static.conditional_period(id, standard, time, minwall, maxwall, createdAt, updatedtAt) VALUES
(4, 1, '16 h ± 1 h', 32, 9999999, '2023-12-04 21:56:39', '2024-03-26 00:24:31');