--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 30/5/2024 19:42:30
-- Server version: 8.3.0
--

SET NAMES 'utf8mb4';

INSERT INTO stel_db_static.endcap(id, standard, encap, createdAt, updatedAt) VALUES
(1, 1, 'Tipo A', '2024-03-31 23:07:41', '2024-03-31 23:07:41');
INSERT INTO stel_db_static.endcap(id, standard, encap, createdAt, updatedAt) VALUES
(2, 1, 'Tipo B', '2024-03-31 23:07:51', '2024-03-31 23:07:51');