--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 30/5/2024 19:42:30
-- Server version: 8.3.0
--

SET NAMES 'utf8mb4';

INSERT INTO stel_db_static.enviroment(id, standard, insertFluid, outFluid, createdAt, updatedAt) VALUES
(1, 1, 'Agua', 'Agua', '2024-03-27 02:20:46', '2024-03-27 02:20:46');
INSERT INTO stel_db_static.enviroment(id, standard, insertFluid, outFluid, createdAt, updatedAt) VALUES
(2, 1, 'Agua', 'Liquido', '2024-03-27 02:21:01', '2024-03-27 02:21:01');
INSERT INTO stel_db_static.enviroment(id, standard, insertFluid, outFluid, createdAt, updatedAt) VALUES
(3, 1, 'Agua', 'Aire', '2024-03-27 02:21:31', '2024-03-27 02:21:31');
INSERT INTO stel_db_static.enviroment(id, standard, insertFluid, outFluid, createdAt, updatedAt) VALUES
(4, 2, 'Agua', 'Aire', '2024-03-27 02:21:46', '2024-03-27 02:21:46');