--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 30/5/2024 19:42:30
-- Server version: 8.3.0
--

SET NAMES 'utf8mb4';

INSERT INTO stel_db_static.test_type(id, standard, testType, createdAt, updatedAt) VALUES
(1, 1, 'Prueba de Resistencia con Presión Constante', '2024-03-27 02:22:38', '2024-04-01 11:10:46');